README.md
This fixes some paths in the README file, making it simpler for new people to use tlcpack.
Closes #21
=> Fix paths from the README file

scripts/build_pip_wheel.sh
This allows to build packages for a specific TVM git hash via command line.
=> Add --hash to scripts build_pip_wheel.sh

scripts/patch_name.sh
During the migration to `black` formatting in TVM 0.8, the use of double-quotes was adopted, so this script needs to be fixed to cope with both single and double-quotes, during the name patching process.
=> Make scripts/patch_name.sh to be compatible with TVM 0.7 and 0.8

scripts/build_pip_wheel.sh
Previously it was necessary to create a "pip" directory manually to avoid this script to crash. This was because of the assumption made by the definition of `$PIP_DIR`.
With this change, we assume they will be at the same level as scripts.
Closes #20
=> Use $SCRIPT_DIR to infer the location of ../docker and ../pip

docker/Dockerfile.package-cpu
The previous version we were using, had some out-of-date repository definitions. Updating to the same manylinux2010 image, from a more recent tag.
The error I see when trying to rebuild the Docker images with the current definition is:
```
$ ./build_image.sh cpu
DOCKER IMAGE NAME: tlcpack/package-cpu:0.1
Sending build context to Docker daemon  31.74kB
Step 1/13 : FROM quay.io/pypa/manylinux2010_x86_64:2020-08-20-df89e22
---> 2d0471711e4c
Step 2/13 : COPY install/centos_install_core.sh /install/centos_install_core.sh
---> Using cache
---> 13c0f0f50547
Step 3/13 : RUN bash /install/centos_install_core.sh
---> Running in a143645f3e46
Loaded plugins: fastestmirror, ovl
Setting up Install Process
Determining fastest mirrors
Error: Cannot find a valid baseurl for repo: base
YumRepo Error: All …
```
=> Update manylinux2010 to a recent version.

README.md, scripts/build_pip_wheel.sh, scripts/build_tvm.sh
Add a `--tvm-url` option to build wheels from a specific fork or repo. 
* Add `--tvm-url` option to `build_pip_wheel.sh` and `build_tvm.sh`;
* Allow pip packages to be created from a specific TVM git repo;
* Add some information to inform users that more options are available (directing them to `--help` option);
* Minor cosmetics on `--help` options.
cc @tqchen @icemelon9
=> Add option to build TVM from a specific repository with --tvm-url.

docker/Dockerfile.package-cpu, docker/Dockerfile.package-cu100, docker/Dockerfile.package-cu101, docker/Dockerfile.package-cu102, docker/install/centos_install_arm_ethosn_driver_stack.sh, scripts/build_tvm.sh
Enable Arm Ethos-N NPU support on packages generated using tlcpack
* Add a script to compile the Arm Ethos-N NPU driver stack, to be added on the produced wheel packages
* Add USE_ETHOSN directive on the TVM builder script
=> Enable Arm Ethos-N NPU support on packages generated using tlcpack

scripts/build_pip_wheel.sh
Remove unnecessary quotes from `--tvm-url` script call
=> Fix quoting on --tvm-url.

docker/Dockerfile.package-cpu, docker/Dockerfile.package-cu100, docker/Dockerfile.package-cu101, docker/Dockerfile.package-cu102, docker/install/centos_install_arm_compute_library.sh, scripts/build_tvm.sh
Add support to Compute Library for Arm Architecture (ACL)
* Add package support to install ACL 21.02
* Include option to build TVM on Linux using ACL
=> Add support to Compute Library for Arm Architecture (ACL)

README.md, docker/Dockerfile.package-cpu, docker/install/centos_install_arm_ethosn_driver_stack.sh, docker/install/centos_install_cmake.sh, docker/install/centos_install_core.sh
Updates the manylinux base image to 2014 to address the incompatibility
of cmake in the 2010 image for building LLVM.
Co-authored-by: Leandro Nunes <Leandro.Nunes@arm.com>
=> Update Docker CPU image to manylinux2014

.github/workflows/wheel_manylinux_nightly.yaml, .github/workflows/wheel_winmac_nightly.yaml, README.md, common/sync_package.py, wheel/build_wheel_manylinux.sh
- Add build script in wheel folder that is based on the original one in script folder (scripts/build_pip_wheel.sh=>wheel/build_wheel_manylinux.sh)
- Remove the tvm cloning part and left that to the workflow
- Remove the quick testing part
- Use the same name patching and syncing mechanism via common/sync_package.py
- Add github actions to build the manylinux matrix, more matrix value of cuda config and image name can be added.
Co-authored-by: Chris Hoge <chris@hogepodge.com>
=> [WORKFLOW] Manylinux wheel.

common/sync_package.py
Add a `--revision` argument to `sync_package.py`
* `--revision` defaults to `origin/main`, which was the previously hard coded value
* It allows packages to be generated from any revision, branch or tag.
=> Add a --revision argument to sync_package.py

common/sync_package.py
Add help descriptions and metavars to argparse arguments for this command line. The main intention is to make these scripts easier to maintain for the future.
cc @tqchen and @hogepodge for reviews
=> Improve usability of common/sync_package.py with help descriptions.

wheel/build_wheel_manylinux.sh
Currently we don't have utvm enabled by default in a regular TVM build. This PR adds USE_MICRO ON so that the package contains utvm.
Motivated by https://github.com/apache/tvm/pull/8086, which makes utvm mandatory as a dependency for tvmc.
cc @gromero @areusch @tqchen for reviews
=> Enable USE_MICRO on tlcpack build.

docker/install/centos_install_arm_compute_library.sh
This PR changes ACL version from 21.02 to 21.05
*ACL stands for "Compute Library for the Arm® Architecture"
=> Changed ACL version from 21.02 to 21.05

jenkins/JenkinsFile-rebuild-docker-images
This is a draft Jenkins pipeline for us to daily build TVM CI docker images.
* The new pipeline is able to build the TVM Docker images and upload them to Docker Hub
* It makes sure that all images are guaranteed to use the same TVM git hash, using a timestamp and short hash, e.g. ci_cpu:2021_07_14-145016-c16d61b
=> Add new Jenkins pipeline to build TVM CI docker images

.github/workflows/prune_nightly.yaml, wheel/wheel_prune_and_sync.py
Update https://tlcpack.ai/wheels only with checked valid URLs:
* This is to tackle a problem in which a corrupted file is uploaded to GitHub, and the https://tlcpack.ai/wheels blindly updates the list of wheels based on file names
* It adds further checking to validate the URLs being considered for updates
* Fixes #54
cc @tqchen for reviews
=> Update https://tlcpack.ai/wheels only with checked valid URLs

jenkins/JenkinsFile-rebuild-docker-images
Just a minor fix in the error message, I captured this morning when the job failed.
cc @tqchen
=> Fix log message to display TVM hash when image build fails.

wheel/build_wheel_manylinux.sh
This is needed so that we can build packages that will include `standalone_crt` directory as `data_files`.
I'll send a counterpart PR on TVM to enable the inclusion of the crt.
cc @areusch @tqchen @Mousius for reviews.
=> Set USE_MICRO_STANDALONE_RUNTIME ON in the Linux wheel builds

wheel/build_wheel_manylinux.sh
Given we recently added support for Arm(R) Ethos(TM)-U NPU in TVM, this change enables "USE_ETHOSU" as part of the tlcpack build.
Related to https://github.com/apache/tvm/pull/8854.
cc @tqchen @areusch @icemelon @jroesch for reviews and merge when possible.
=> Enable Arm(R) Ethos(TM)-U NPU as part of tlcpack.

docker/install/centos_build_llvm.sh
Fix GitHub API usage to get minor LLVM version from releases API.
* By default, the API returns the first 30 results. As the version we use gets older, we now need to get more results for 10.x to appear in the results. This breaks the way we resolve LLVM versions to be built
* This change increase the number of results from 30 to 50
Reference for the parameters being used: https://docs.github.com/en/rest/reference/repos#releases
cc @icemelon @tqchen @areusch @Mousius for reviews
=> Fix GitHub API usage to get minor LLVM version from releases API.

README.md
There is a wrong script name `build_manylinux_wheel.sh` in README.md,  actually this script named  `build_wheel_manylinux.sh`. This PR aims to fix this minor error.
=> Fix wrong script name in README.md

docker/install/centos_install_arm_compute_library.sh
This PR changes ACL version from 21.05 to 21.08
*ACL stands for "Compute Library for the Arm® Architecture"
=> Changed ACL version from 21.05 to 21.08

conda/recipe/build.sh, wheel/build_lib_osx.sh, wheel/build_wheel_manylinux.sh
* This is to workaround an issue caused by conflicting LLVM
versions, first observed by since we updated Pytorch in TVM
* Discussion at: https://github.com/apache/tvm/issues/9362
=> Set HIDE_PRIVATE_SYMBOLS ON for manylinux/osx/conda packages.

wheel/build_wheel_manylinux.sh
This enables CMSIS-NN support in tlcpack builds.
=> Enable CMSIS-NN support in tlcpack builds

jenkins/JenkinsFile-rebuild-docker-images
This is a follow up PR to https://github.com/apache/tvm/pull/10263
After https://github.com/apache/tvm/pull/10263 is merged, we can merge this PR to add ci-hexagon build.
=> [CI] Add ci-hexagon image build

docker/install/centos_install_arm_ethosn_driver_stack.sh
As Dockerfile.package-cu102 does not have Python 3.6 (EOL), moving dependency installation script `centos_install_arm_ethosn_driver_stack.sh` to use Python 3.7 instead.
cc @tqchen @areusch @Mousius
=> Update centos_install_arm_ethosn_driver_stack.sh to use Python 3.7

docker/Dockerfile.package-cu102
* Removing it due to deprecation and not being present in the latest version on the base image
Base image information:
```
pytorch/manylinux-cuda102           latest                      2146d9ccbb6e
```
cc @areusch @tqchen @Mousius
=> Remove Python 3.6 installation from Dockerfile.package-cu102

.github/workflows/conda_cpu_nigthly.yaml, .github/workflows/wheel_winmac_nightly.yaml, conda/recipe/bld.bat, wheel/build_lib_win.bat
GitHub says Windows 2016 is deprecate from 1st April 2022, so this patch update the infra to use Windows 2019 instead.
This is needed to unblock https://github.com/tlc-pack/tlcpack/pull/102.
cc @areusch @tqchen @Mousius for reviews
=> Update infrastructure to use Windows 2019

.github/workflows/wheel_winmac_nightly.yaml
Currently used `python` binary causes this script to be run with Python 2 (default on Mac). This patch updates to use Python 3.
cc @areusch @driazati @Mousius for reviews
=> Update Windows/Mac usage of sync_package.py to Python 3

.github/workflows/conda_cpu_nigthly.yaml, .github/workflows/wheel_manylinux_pypi_nightly.yaml, common/sync_package.py, wheel/build_wheel_manylinux.sh
Add a new GitHub Action pipeline to run every night, to upload "CPU" (i.e. non-CUDA) packages to PyPI under apache-tvm namespace, using the latest code from 'main'.
cc @areusch @driazati
=> Enable package uploading to PyPI using a new GitHub Action pipeline

jenkins/JenkinsFile-rebuild-docker-images, jenkins/JenkinsFile-validate-docker-images
This removes the `-DOCKER` suffix from the node requirements as the only
differentiation in CI nodes right now is by platform (ARM, GPU, CPU)
cc @areusch @konturn
=> Consolidate node names

.github/workflows/wheel_winmac_nightly.yaml, docker/Dockerfile.package-cpu, docker/Dockerfile.package-cu100, docker/Dockerfile.package-cu101, docker/install/ubuntu_install_python.sh, wheel/build_wheel_manylinux.sh
As Python 3.6 reached EOL status in 31/dec/2021, we are now phasing out packaging for this Python version.
cc @tqchen @driazati @areusch @Mousius 
closes #107
=> Deprecate Python 3.6 packaging

jenkins/JenkinsFile-validate-docker-images
This was changed in b228de4 and partially reverted in 955de4a, but currently it is causing the validation job to fail to resolve local variables.
Example of job failing: https://ci.tlcpack.ai/blue/organizations/jenkins/docker-images-ci%2Fdaily-docker-image-validate/detail/daily-docker-image-validate/101/pipeline
cc @driazati @areusch @Mousius for reviews
=> Revert quoting to Jenkins nightly validation job

.github/workflows/wheel_winmac_nightly.yaml
It looks like Python 3.7/3.8 now needs `MACOSX_DEPLOYMENT_TARGET=10.15`
See: https://github.com/cython/cython/pull/4793
@leandron
=> Fix build of OSX wheels

jenkins/JenkinsFile-rebuild-validate-rvm-images
This PR removes the version from the names of the microTVM reference VMs on Vagrant Cloud. Please see https://github.com/apache/tvm/pull/11629 for details about why this makes sense.
=> Remove microTVM RVM version suffix

jenkins/JenkinsFile-rebuild-validate-rvm-images
Automatically build and upload the Arduino RVM image to the cloud hub. This change should fix the broken `spresense` test on the microtvm nightly run.
=> Build Arduino RVM image on Jenkins

.github/workflows/wheel_manylinux_pypi.yaml
Using a nightly cadence to publish packages on PyPI made our quota to run out in about 3 months, so I'm changing the cadence to be weekly, so that we can have a regular "dev drop", while we try to negotiate a bump in our quota.
This only applies to packages published on PyPI https://pypi.org/manage/project/apache-tvm/releases/ which I manually cleaned up to keep one build per week since April/2022.
cc @areusch
=> Move `apache-tvm` PyPI package cadence to be weekly

.github/workflows/conda_gpu_nigthly.yaml, .github/workflows/wheel_manylinux_nightly.yaml, .github/workflows/wheel_manylinux_pypi.yaml, docker/Dockerfile.package-cpu, docker/Dockerfile.package-cu100, docker/Dockerfile.package-cu101, docker/Dockerfile.package-cu102, docker/bash.sh, docker/install/centos_install_python_package.sh, docker/install/ubuntu_install_python_package.sh, wheel/run_tests.sh
This PR runs the python unit tests as part of the nightly build. 
Since at the moment there are some failing tests, I do an `|| true` to ignore the return code of the `run_tests.sh` command and [keep the green tick-mark](https://github.com/actions/toolkit/issues/399) in the actions section.
@areusch
=> Run tests in wheel

wheel/wheel_prune_and_sync.py
PEP503 (https://peps.python.org/pep-0503/) requires that a wheel directory must be a valid HTML5 page.
cc @leandron @tqchen
=> Generate PEP503 compliant wheel directory

docker/Dockerfile.package-cu110, docker/Dockerfile.package-cu111, docker/Dockerfile.package-cu113
I checked the errors in the latest pip build and the root cause should be just the CUDA path. Without explicitly pointing to the right CUDA version, Cmake will still find CUDA 10.2 in these images.
Meanwhile, I tried to debug the conda build failure, but I could only say it should be due to the difference conda environment in these images, but I have no idea how to resolve them.
cc @areusch @tqchen
=> [CUDA] Fix manylinux build

README.md, docker/Dockerfile.package-cpu_aarch64, docker/build_image.sh, docker/install/centos_install_arm_ethosn_driver_stack.sh, docker/install/centos_install_core_aarch64.sh
Add support to generate native AArch64 packages with TVM. It was tested to generate cpu targeted wheel packages using
`manylinux2014_aarch64` on AArch64. We still can't produce these natively as GitHub Actions doesn't support AArch64.
cc @driazati @areusch @Mousius @tqchen
=> Add support for AArch64 wheel Python packages

docker/install/centos_build_llvm.sh
We are currently using GitHub API to discover what is the latest 10.0.x minor release in LLVM. As LLVM now releases a few more versions the number of results we are retrieving (50) is not enough.
This patch increases the number of results to 100, so that we can get the information we need.
Sample URLs:
- 50 results (does not cover 10.0.x): https://api.github.com/repos/llvm/llvm-project/releases?per_page=50
- 100 results (cover 10.0.x): https://api.github.com/repos/llvm/llvm-project/releases?per_page=100
Suggested search `LLVM 10.0`.
cc @Mousius @tqchen @areusch @driazati
=> Increases LLVM releases version results from GitHub API

docker/install/centos_install_arm_ethosn_driver_stack.sh
Updates the driver stack version to v22.08.
~Note: marking as WIP as this is dependent on https://github.com/apache/tvm/pull/12650~
cc @leandron
=> [ETHOSN] Update NPU driver stack to v22.08

docker/install/centos_install_cmake.sh
See #138.
As mentioned, to fix the CI, the newly build images also have to be tagged and used in the workflows.
cc @Mousius @tqchen @driazati @leandron
=> [Docker] Use up-to-date version of CMake an all images

docker/Dockerfile.package-cpu
Should resolve #142.
Once merged, I will do a followup PR hopefully fixing #141 and #138 as well.
=> [Docker] Use pytorch base images for tlcpack/package-cpu to fix manylinux2014 compliance

.github/workflows/conda_gpu_nigthly.yaml, .github/workflows/docker_images.yaml, .github/workflows/wheel_manylinux_nightly.yaml, common/sync_package.py, conda/recipe/meta.in.yaml, docker/build_image.sh, wheel/build_wheel_manylinux.sh
- Fixed Conda builds by Increasing the allowed version of the CUDNN package and dropping support for CUDA 11.0
- Enable builds for CUDA 11.6 (not tested yet)
- Fix final issue with manylinux nightly builds
- For consistency drop CUDA 11.0 support for other workflows as well
MacOS errors are covered in #140.
=> Fix remaining CI Errors

wheel/wheel_prune_and_sync.py
It seems like the "Prune-Nightly" job broke yesterday: https://github.com/tlc-pack/tlcpack/actions/runs/3327332266/jobs/5502020456
```
Traceback (most recent call last):
File "/home/runner/work/tlcpack/tlcpack/wheel/wheel_prune_and_sync.py", line 172, in <module>
main()
File "/home/runner/work/tlcpack/tlcpack/wheel/wheel_prune_and_sync.py", line 163, in main
group_map = group_wheels(wheels)
File "/home/runner/work/tlcpack/tlcpack/wheel/wheel_prune_and_sync.py", line 63, in group_wheels
gkey, order = extract_group_key_order(asset.name)
File "/home/runner/work/tlcpack/tlcpack/wheel/wheel_prune_and_sync.py", line 50, in extract_group_key_order
pub_ver = [int(x) for x in ver[:dev_pos].split(".")]
File "/home/runner/work/tlcpack/tlcpack/wheel/wheel_prune_and_sync.py", line 50, in <listcomp> …
```
=> [CI] fix broken handling of release candidates in wheel_prune_and_sync.py script

conda/anaconda_prune.py
Had to port #146 to Conda as well to fix CI.
HOWEVER I found the actual cause of that RC-related issues:
The rc tag for the latest TVM should be `v0.10.rc0` Instead of `v0.10.0rc0`. Renaming that tag leads to the expected behavior for nightly builds based on the `v0.10.dev0` instead of `v0.10.0rc0`.
@tqchen Should we really add a workaround to deal with that mistake/inconsistency or just recreate the tag in the upstream repo with the proper name?
=> [CI] fix broken handling of release candidates in anaconda_prune.py

common/sync_package.py
In some circumstances we would like to skip the checkout stage, in order to run the package sync on an existing checkout.
In this case it is not necessary and in some cases, undesirable to run the checkout again so this patch adds logic to bypass it when required.
Unless the --skip-checkout option is passed, existing checkout logic remains unchanged by this patch.
CC @leandron @areusch @Mousius @driazati for review
=> Add logic to skip the Git checkout

.github/workflows/conda_gpu_nigthly.yaml, .github/workflows/wheel_manylinux_nightly.yaml, .github/workflows/wheel_manylinux_pypi.yaml
Bumping up tlcpack/package-* versions to latest
docker images that include support for Arm(R) Ethos(TM)-N
NPU driver 22.11. This should fix tlcpack nightly and pypi CI.
cc @leandron @driazati
=> Update manylinux container tags

docker/Dockerfile.package-cpu_aarch64
* deprecate Python 3.6 support
* brings Python 3.11 support
Note: these changes were used to generate the current AArch64 at https://pypi.org/project/apache-tvm/0.11.1/#files
While we don't have (yet) an automated way to build and publish packages, we need to do the same manual process for x86 packaging and upload.
cc @tqchen @Liam-Sturge @areusch for reviews
=> [AArch64] Update manylinux_aarch64 tag to 2023-03-12-25fd859

docker/Dockerfile.package-cu117, docker/Dockerfile.package-cu118
Currently, tlcpack docker image only has support cuda version <= 11.6, we should move on and support cu117/cu118.
=> Add docker image for cu117 & cu118 

docker/Dockerfile.package-cpu, docker/Dockerfile.package-cpu_aarch64, docker/Dockerfile.package-cu102, docker/Dockerfile.package-cu110, docker/Dockerfile.package-cu111, docker/Dockerfile.package-cu113, docker/Dockerfile.package-cu116, docker/install/centos_build_llvm.sh
Update LLVM version from 10.0.x to align with the currently used in TVM, which is 15.0.x (specifically 15.0.7 at the time this PR was raised) so that we can have feature parity with TVM built from source and TVM in packages.
This is a required counterpart change as we moved to LLVM in TVM.
cc @areusch @Liam-Sturge @neildhickey @NicolaLancellotti for reviews
=> [LLVM] Update LLVM from 10.0.x to 15.0.x

jenkins/JenkinsFile-PyPI-packaging
This patch adds a new Jenkins pipeline for packaging. This is a migration of the current Github actions workflow of uploading a Tensor learning compiler binary distribution (tlcpack) to PyPI.
This new packaging pipeline implements a parallel step that creates and uploads AArch64 packages, which is something not present in the Github actions job it is intended to replace.
I have tested the pipeline [here](https://ci.tlcpack.ai/blue/organizations/jenkins/pypi-packaging%2Fregular-pypi-package-upload/detail/regular-pypi-package-upload/4/pipeline), with some minor modifications so that the packages were uploaded to my personal test.pypi account. The code submitted in this patch will attempt to upload to the apache-tvm production package.
cc @areusch @driazati @tqchen @leandron
=> [CI] Add new PyPI packaging Jenkins pipeline

jenkins/JenkinsFile-PyPI-packaging
Token is stored under a different name in Jenkins. Updating the script to match.
cc @leandron @areusch @tqchen @Mousius
=> [CI] Fix PyPI api token

docker/Dockerfile.package-cpu, docker/Dockerfile.package-cpu_aarch64, docker/install/centos_build_llvm.sh
Align the LLVM version with main TVM repository, so that packages contain the same level of functionality as building from source.
Simplify the script build clang and LLVM as part of a one step build, as recommended by the official clang docs at https://clang.llvm.org/get_started.html
Updates validated in both CPU images.
cc @tqchen @areusch @Liam-Sturge @ashutosh-arm @neildhickey
=> [LLVM] Update LLVM from 15.0.x to 16.0.x

jenkins/JenkinsFile-PyPI-packaging
Changed the pipeline to enable the user to specify which Git ref to use for the checkout and package build. Removed additional checkout logic causing issues building the correct package.
Parameterised other variables which were previously only able to be modified within the script. Configured these with sensible default values that can be modified via the Jenkins user interface.
Minor changes to formatting.
cc @leandron @areusch @tqchen @konturn @Mousius
=> [CI] Modify PyPI packaging Jenkins pipeline

docker/install/centos_install_arm_compute_library.sh
Update Compute Library to follow latest developments in 23.05.
Changelog: https://arm-software.github.io/ComputeLibrary/v23.05
Counterpart change in TVM at https://github.com/apache/tvm/pull/15344
cc @neildhickey @ashutosh-arm @lhutton1 for reviews
=> [ACL] Update Compute Library to v23.05
