.github/workflows/conda_prune_nightly.yaml, conda/anaconda_prune.py, conda/sync_version.py
=> [CONDA] Add Conda Nightly Prune

.github/workflows/prune_nightly.yaml, .gitignore, conda/anaconda_prune.py, conda/build-environment.yaml, wheel/wheel_prune_and_sync.py, wheel/wheel_upload.py
=> [WHEEL] Introduce script to prune wheels

docker/install/centos_install_arm_ethosn_driver_stack.sh
- Updated default Ethos-N driver stack to 21.02
=> [ETHOSN] Add support for Ethos-N 21.02 driver stack release

common/sync_package.py
Decouple package name from build type in `common/sync_package.py`.
* It creates a new (optional) parameter `--package-name`, that allows different build types (at the moment two: `tlcpack` and `tlcpack-nightly`) to be generated with any specified name.
* For compatibility reasons it defaults the package name to the specified build type
cc @tqchen and @hogepodge for reviews
=> Decouple package name from build type in common/sync_package.py

common/sync_package.py
Improve sync_packages to patch tvm/_ffi/libinfo.py with tlcpack version
- This makes the version reported by TVM to be coherent with the `tlcpack` version it is running from.
- Fixes #63
cc @tqchen for reviews
=> Improve sync_packages to patch tvm/_ffi/libinfo.py with tlcpack version.

.github/workflows/prune_nightly.yaml
* Folow up from #65 that added an invalid pip command
cc @tqchen
=> Fix pip command in GitHub Action

jenkins/JenkinsFile-rebuild-docker-images
Meant to disambiguate staging and production docker-daily builds.
=> Parametrize DOCKERHUB_USER environment variable

.github/workflows/prune_nightly.yaml
This is a hotfix for conda out of space problem right now at main.
cc @areusch @leandron
=> [CONDA] Add conda prune script for all repos

common/sync_package.py
cc @leandron @junrushao1994 @areusch
=> [VERSION] Use v0.7 for stable build

docker/install/centos_install_arm_ethosn_driver_stack.sh
- Updated Ethos-N driver stack to 21.08
=> [ETHOSN] Add support for Ethos-N 21.08 driver stack release

jenkins/JenkinsFile-validate-docker-images
=> [Hexagon][Docker] Add validation for CI hexagon

wheel/build_lib_osx.sh, wheel/build_wheel_manylinux.sh
There are still differences with support for other configuries between
these 2 packages but this appears to be boolean options that can be
fixed easily.
I don't have a way of building this on osx but would like to try the resultant
build if it passes CI .
=> Sync osx builds

jenkins/JenkinsFile-validate-docker-images
=> Fix Validation Jenkins File 

common/sync_package.py
Update the version string to reflect the latest TVM release.
cc @tqchen @driazati @areusch @manupa-arm
=> Update the TVM release version string to v0.9.0

jenkins/JenkinsFile-rebuild-docker-images
Follow-up to https://github.com/apache/tvm/pull/12230.
@driazati @alter-xp @PhilippvK
=> Add ci_riscv to daily docker image rebuild

jenkins/JenkinsFile-rebuild-docker-images, jenkins/JenkinsFile-validate-docker-images
=> Rename ci_qemu to ci_cortexm

jenkins/JenkinsFile-rebuild-docker-images, jenkins/JenkinsFile-validate-docker-images
=> Add ci_minimal to nightly docker rebuild

docker/install/centos_install_arm_ethosn_driver_stack.sh
Updates the driver stack version to v22.05.
cc @Leo-arm @leandron
=> [ETHOSN] Update NPU driver stack to v22.05

.github/workflows/docker_images.yaml, docker/Dockerfile.package-cpu, docker/Dockerfile.package-cu110, docker/Dockerfile.package-cu111, docker/Dockerfile.package-cu113, docker/Dockerfile.package-cu116, docker/install/centos_install_core.sh, docker/install/centos_install_python_package.sh
This adds a nightly build and push for the Docker images so it's easier to keep them up to date
=> Automate Docker image builds

.github/workflows/conda_gpu_nigthly.yaml, .github/workflows/wheel_manylinux_nightly.yaml, .github/workflows/wheel_manylinux_pypi.yaml, wheel/build_wheel_manylinux.sh
=> Update Manylinux container tags

docker/install/centos_install_arm_ethosn_driver_stack.sh
Updates the driver stack version to v22.11.
cc @leandron @driazati
=> [ETHOSN] Update NPU driver stack to v22.11

docker/install/centos_install_arm_compute_library.sh
Changelog for this version can be found at:
https://arm-software.github.io/ComputeLibrary/v22.11/
cc @leandron @driazati
=> [ACL] Update Compute Library to v22.11

docker/install/centos_install_arm_compute_library.sh
Changelog can be seen at https://arm-software.github.io/ComputeLibrary/v23.02.1/
=> [CL] Update Compute Library from v22.11 to v23.02.1

common/sync_package.py
Updates the latest stable version so that packages are generated correctly.
cc @areusch @neildhickey @ashutosh-arm @Liam-Sturge for reviews
=> [Release] Update stable version to v0.12.0 for wheel packaging.

docker/install/centos_install_arm_compute_library.sh
Update Compute Library to follow latest developments in 23.05.1.
Changelog: https://arm-software.github.io/ComputeLibrary/v23.05.1
cc @Liam-Sturge @ashutosh-arm for reviews.
=> [ACL] Update Compute Library to v23.05.1

docker/install/centos_install_arm_compute_library.sh
Update Compute Library to follow latest developments in 23.08
Changelog: https://arm-software.github.io/ComputeLibrary/v23.08
cc @Liam-Sturge @ashutosh-arm for reviews
=> [ACL] Update Compute Library to v23.08

docker/Dockerfile.package-cpu_aarch64
This was validated by building the wheel following instructions in the README.md
cc @Liam-Sturge @neildhickey @leandron @ashutosh-arm
=> [LLVM] Update `cpu_aarch64` LLVM to 17.0.x
